### ISSUE TITLE
add type "Symbol.iterator" to be actually an iterator

### ISSUE THREAD

**Issue by hasezoey** [3rd-Eden/find-package-json#10]
currently when doing: `for (const found of finder(startDirectory)) { }`
it errors with `Type 'FinderIterator' must have a '[Symbol.iterator]()' method that returns an iterator. ts(2488)`

this means, `FindIterator` is not an actual iterator

my current fix is:
```ts
interface CustomFinderIterator extends FinderIterator { // Extend this interface to make it overwrite-able instead of converting to "unknown/any" first
  [Symbol.iterator](): Iterator<Package>; // this is because in the "for..of" it only returns the "value" field
}

for (const found of finder(startDirectory) as CustomFinderIterator) { }
```

**Comment by ljharb** [comment]
This looks like a TypeScript error, and an incorrect one at that. This package doesn't have types in it. Perhaps this is an issue with https://www.npmjs.com/package/@types/find-package-json instead?

**Comment by hasezoey** [comment]
whoops, sorry didnt notice this package dosnt provide them directly

PS: but still, when using the workaround (to make types compatible), there is still the problem that the extra value `filename` cannot be read in something like an for..of loop

**Comment by ljharb** [comment]
That [was intentional](https://github.com/3rd-Eden/find-package-json/blob/master/index.js#L80-L84). Don't use a for..of loop, and you'll be able to access to filename also - but also, `value.__path` contains the filename data as well.

**Comment by hasezoey** [comment]
for anyone interested, i made an issue in the types repo: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51360

i will close this, because of what @ljharb said
(`value.__path` definitely helped, thanks)
