### ISSUE TITLE
Add iterator protocol

### ISSUE THREAD

**Issue by glensc** [3rd-Eden/find-package-json#12]
Currently, it just throws:

```
TypeError: finder is not iterable
```

```js
  const finder = require('find-package-json');
  for (const f of finder) {
    console.log(f)
  }
```

**Comment by ljharb** [comment]
`finder` is a function, it isn't and shouldn't be iterable. https://github.com/3rd-Eden/find-package-json/blob/master/index.js#L34-L40 means that the *return value* of that function will be iterable, however.

**Comment by glensc** [comment]
Indeed. my bad. this works:

```ts
import finder from "find-package-json";

for (const f of finder(__dirname)) {
  console.log(f);
}
```

**Comment by glensc** [comment]
@ljharb 


🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

PS: gitlab has a bug and you need to reload a page before `y` works.

**Comment by ljharb** [comment]
yes, i'm aware, but i'm not concerned about this line changing and in practice it doesn't really matter.
