### ISSUE TITLE
Stop shipping 'fixture/broken/' to npm

### ISSUE THREAD

**Issue by ryan953** [3rd-Eden/find-package-json#5]
We need to ignore these files. Test files don't really need to be installed by package consumers, and by default projects with flow enabled will trip up over the broken files in here. It's not a great experience.

**Comment by 3rd-Eden** [comment]
Why not fix flow?

**Comment by ryan953** [comment]
We could definitely suggest something to flow directly. I'm not sure what to ask of them though. 

In this case you have an invalid json file (invalid on purpose) that ends up in the node_modules folder. 
It makes sense that they find the json files in node_modules, because those files have structure and types. They can be imported into any JS module. So inspecting files and preserving g types makes sense in that case. 

So you have a better suggestion, I'll take it over there
